# Generated by Django 5.1.1 on 2024-10-02 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('apelido', models.CharField(blank=True, max_length=255, null=True)),
                ('código', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('cep', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('up', models.CharField(blank=True, max_length=2, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cnpj', models.CharField(max_length=50, null=True)),
                ('ie', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logo')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('código', models.CharField(blank=True, max_length=255, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(blank=True, max_length=25, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('custo', models.IntegerField(blank=True, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('itens', models.PositiveIntegerField()),
                ('desconto', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('recebimento', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.IntegerField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(through='business.PedidoItem', to='business.produto'),
        ),
    ]
