# Generated by Django 5.1.1 on 2024-10-02 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
