# Generated by Django 5.1.1 on 2024-09-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
    ]
