# Generated by Django 5.1.1 on 2024-10-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='cpf_cnpj',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='inscricao_estadual',
            new_name='ie',
        ),
        migrations.RemoveField(
            model_name='business',
            name='segmento_atuacao',
        ),
        migrations.RemoveField(
            model_name='business',
            name='tipo_pessoa',
        ),
    ]
